### ISSUE TITLE
this doesn't seem to work... the .deb file is not downloaded correctly. 

### ISSUE THREAD

**Issue by jacksnodgrass** [credija/openfire#1]
https://www.igniterealtime.org/downloads/download-landing.jsp?file=openfire/openfire_4.3.2_all.deb

- that loads a .html page that has a link and an auto download to the real .deb file. 

As-is.. the wget command to download the .deb file does not work. 

- jack

**Comment by kevinfaveri** [comment]
This image will not be supported anymore. As an alternative you can use: https://github.com/sameersbn/docker-openfire
